settings:
  title: 'status.qian.io'
  url: 'https://status.qian.io' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: url-shortener
    name: url-shortener
    url: 'https://qian.to/rest/v3/'
    expectStatus: 401

  - id: report
    name: analytics
    url: 'https://qian.report/'
    expectStatus: 200
    
  - id: feedback
    name: http-status
    url: 'https://qian.stream/'

  - id: netsage
    name: netsage
    url: 'https://netsage.qian.io/'
    
  - id: ludwig-lite
    name: lite.ludwig
    url: 'https://lite.ludwig.qian.io'
    
  - id: lift-aws-us-west-2
    name: us-west-2.aws.lift
    url: 'https://us-west-2.aws.lift.ludwig.qian.io'
    linkable: false

  - id: lift-aws-eu-central-1
    name: eu-central-1.aws.lift
    url: 'https://eu-central-1.aws.lift.ludwig.qian.io'
    linkable: false
  
  - id: lift-alibaba-eu-west-1
    name: eu-west-1.alibaba.lift
    url: 'https://eu-west-1.lift.ludwig.qian.io'
    linkable: false

  - id: lift-alibaba-ap-east-1
    name: ap-east-1.alibaba.lift
    url: 'https://ap-east-1.alibaba.lift.ludwig.qian.io'
    linkable: false